### ISSUE TITLE
Unable to understand how to use lmt_to_gltf and lmt_to_json

### ISSUE THREAD

**Issue by Esfiel** [PredatorCZ/RevilLib#6]
G'evening and apologize for the trouble, but, as subject i'm unable to understand how i should use these 2 commands properly.
I'll try to describe my settings as clearly as possible:
 
I was trying to convert Dragon's dogma online .lmt BUT it didn't work , unsure if they were supported or whatever, i tried with RES 6 and the result was the same. I'll use RES 6 file as example.
I managed to extract the arc files and convert the .mod to .glb without a problem.
My directory is `E:\RevilToolset`
Inside `revil_toolset.config` i set both
```xml
<lmt_to_gltf
	model-source="EM3100/em3100.glb" />
<lmt_to_json
	model-source="EM3100/em3100.glb" />
```
I drag and drop `em3100_g00.lmt` lmt file onto `lmt_to_gltf` and it tells me that it was expecting a batch json (it's kinda misleading?) but ok, there's the `lmt_to_json`, in this case if i drag and drop the file i get this 
![immagine_2024-03-22_192836744](https://github.com/PredatorCZ/RevilLib/assets/164550968/da5b0b7c-d2cf-4766-ba55-c9d7e6823404)
Nothing gets created; reading [this issue](https://github.com/PredatorCZ/RevilLib/issues/4) lead me [here](https://github.com/PredatorCZ/Spike/wiki/Spike---Batching): i try to create a `batch.json` like this
```json
[
    [
        "EM3100/em3100.glb",
        "EM3100/em3100_g00.lmt",
        "EM3100/em3100_g01.lmt",
    ]
]
```
but with `lmt_to_gltf` i'm not getting anything... so i'm at loss on what i'm missing as i couldn't find much else regarding this.

In any case, thank you for the tools and, in advance, for your time~

**Comment by PredatorCZ** [comment]
Hi, `model-source` was used a long time ago and is unused since. I forgot to remove this setting.
You need to load json itself, not lmt.

**Comment by Esfiel** [comment]
Sorry for the late answer~

> You need to load json itself, not lmt. 

Guess i'm still doing it wrong...?
considering em3100_g00batch.json:

```
[
    [
        "EM3100/em3100.glb",
        "EM3100/em3100_g00.lmt",
        "EM3100/em3100_g01.lmt",
    ]
]
```

If i try to use this file with lmt_to_gltf i'm not getting any files or errors out of it
![immagine_2024-03-27_123233835](https://github.com/PredatorCZ/RevilLib/assets/164550968/6839ccf9-5ac5-42e1-b4b7-1e50220cc0b6)

**Comment by PredatorCZ** [comment]
Maybe it will silently fail due to invalid json format, gonna need to check release build since it always error in debug.
Try:
```json
[
    [
        "EM3100/em3100.glb",
        "EM3100/em3100_g00.lmt",
        "EM3100/em3100_g01.lmt"
    ]
]
 ```

Notice that the last array item cannot have `,`. I know it's a dumb json rule, since it's a constant problem for me also. But what can we do...

I assume that parent folder of `EM3100` contains the `em3100_g00batch.json`.

**Comment by Esfiel** [comment]
> Maybe it will silently fail due to invalid json format, gonna need to check release build since it always error in debug. Try:
> 
> ```json
> [
>     [
>         "EM3100/em3100.glb",
>         "EM3100/em3100_g00.lmt",
>         "EM3100/em3100_g01.lmt"
>     ]
> ]
> ```
> 
> Notice that the last array item cannot have `,`. I know it's a dumb json rule, since it's a constant problem for me also. But what can we do...
> 
> I assume that parent folder of `EM3100` contains the `em3100_g00batch.json`.

Thank that solved the issue! 
So my thread itself is solved...... buuut...!
![immagine_2024-03-27_224012712](https://github.com/PredatorCZ/RevilLib/assets/164550968/92743d2d-54d4-4ce7-92ba-fdb3b2a89797)
The process still won't make anything out of it. Dunno if, at this point it has something to do with the files itself

**Comment by PredatorCZ** [comment]
It seems like it's silently crashing. Does your system show assert messages or anything regarding app crashing?
Are you running it from `.cmd` files?

**Comment by Esfiel** [comment]
> It seems like it's silently crashing. Does your system show assert messages or anything regarding app crashing? Are you running it from `.cmd` files?
> 
> It should generate `em3100_out.glb` file.

Nope no warning or anything at all.
Altough i took a look at Event viewer and i found this "error" regarding the revil_toolset, made a text file with the xml version, dunno if you can make something out of it
[crash.txt](https://github.com/PredatorCZ/RevilLib/files/14793485/crash.txt)

The pic was made after i drag-dropped but if i run the cmd manually the result is the same
![immagine_2024-03-28_183801182](https://github.com/PredatorCZ/RevilLib/assets/164550968/dc288f0b-e37d-4b17-aee5-8c5a04d4b1d1)

**Comment by PredatorCZ** [comment]
Yes, the crash event helped a lot. The app crashes on Access Violation. That means something is wrong somewhere.
Possibly poor support for this title. 
I'm gonna need to test it.
It's weird it won't show you any message of any kind that the app crashed. You probably have disabled crash reporting on your OS.

**Comment by PredatorCZ** [comment]
I was able to make it work in v2.8.156.
However dd online uses unbaked IK data, so hands and feet are gonna be wrong.
I have plan for IK resolver (for a few years now, lol), that would fix this.

**Comment by Esfiel** [comment]
> I was able to make it work in v2.8.156. However dd online uses unbaked IK data, so hands and feet are gonna be wrong. I have plan for IK resolver (for a few years now, lol), that would fix this.

Awesome, thank you for you hard work and no problem for DDO, working with wrong hands/feet it's better than not working at all!
Since the main thread found a solution i can mark this as closed.

**Comment by lordabura** [comment]
@Esfiel how run lmt_to_json, not work for me , execute but not generate json file 

![Image](https://github.com/user-attachments/assets/c3ab63e6-a4e2-473f-a751-4fd9fb59ace3)
