### ISSUE TITLE
unknown file types (RESIDENT EVIL CODE VERONICA [PS3])

### ISSUE THREAD

**Issue by modusc896d352** [PredatorCZ/RevilLib#7]
here they are, in no particular order:
0A736313, 1BE1DBEB, 5DF3D947, 6A76E771, 7DB518E8, 09C48A11, 46C78353, 74AFE18C, 108F442E, 0949A1DA, 42940D09, 4356673E, 40171000

**Comment by PredatorCZ** [comment]
Fixed in v2.8.155

**Comment by modusc896d352** [comment]
ok, thanks for the fix
