### ISSUE TITLE
Monster Hunter Stories 2: Error converting using lmt_to_gltf 

### ISSUE THREAD

**Issue by stormygaret15** [PredatorCZ/RevilLib#8]
Is lmt from Stories 2 currently supported? Keep getting error invalid version 68.

![Screenshot (3)](https://github.com/PredatorCZ/RevilLib/assets/83821164/43a5aed4-1ddb-4bd6-926d-d04e730f2822)

**Comment by PredatorCZ** [comment]
No, that version is not supported. Can be added.

**Comment by PredatorCZ** [comment]
Added in v2.8.160

**Comment by stormygaret15** [comment]
Works perfectly! Thank you very much.

**Comment by lordabura** [comment]
@stormygaret15 how run script, not work for me
